### ISSUE TITLE
Inaccurate command description for `where`

### ISSUE THREAD

**Issue by anubha-v-ardhan** [verma-kunal/DevOps-90#7]
Hey @verma-kunal, correct me if I'm wrong

On [Journey/Day09.md](https://github.com/verma-kunal/DevOps-90/blob/main/Journey/Day09.md), the mention 
```
where <command> → to find the location of the executable file of that command
```
is inaccurate. Linux offers two ways to find the location of a binary:
- `whereis` will locate the binary, source and man page for a command. ([see more](https://linux.die.net/man/1/whereis))
- `which` will show the full path of shell command. ([see more](https://linux.die.net/man/1/which))

**Comment by verma-kunal** [comment]
Hey @anubha-v-ardhan , thanks for opening an issue!
So, in UNIX based terminals (like in mac), we can find the location of the executables using the `where` command as well (example below)

To make these notes accessible for other systems as well, I'll add in your point
Thanks :)

![Screenshot 2022-06-20 at 10 06 31 AM](https://user-images.githubusercontent.com/72245772/174526149-5a8bd054-15e6-4152-aece-6e97d29979e3.png)

**Comment by verma-kunal** [comment]
Keeping this issue as `open` to remember the change :)

**Comment by verma-kunal** [comment]
If you are interested, you can make this change as well in that file :)
